#=======================================================================================================================
             project(resources-module LANGUAGES CXX)
#=======================================================================================================================
         add_library(resources-module)
#=======================================================================================================================
    add_subdirectory(core)
#=======================================================================================================================
    add_subdirectory(images)
#=======================================================================================================================
    add_subdirectory(shaders)
#=======================================================================================================================

#=======================================================================================================================
if (ENABLE_EDITOR_FEATURES)
#=======================================================================================================================
    add_subdirectory(tools)
#=======================================================================================================================
endif()
#=======================================================================================================================