#=======================================================================================================================
target_include_directories(${PROJECT_NAME} PRIVATE PUBLIC ..)
#=======================================================================================================================
     target_link_libraries(${PROJECT_NAME} PRIVATE common_module)
#=======================================================================================================================